// packages/svelte/src/Providers.svelte
<script lang="ts">
    import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query';
    import { SvelteQueryDevtools } from '@tanstack/svelte-query-devtools';
    import App from './App.svelte';

    const queryClient = new QueryClient();

    export let hideDevTools = false;
</script>

<QueryClientProvider client={queryClient}>
    <App />
    {#if !hideDevTools}
        <SvelteQueryDevtools initialIsOpen={false} />
    {/if}
</QueryClientProvider>

// packages/react/src/Providers.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { App } from './App';

const queryClient = new QueryClient();

export const Providers = () => (
    <QueryClientProvider client={queryClient}>
        <App />
        <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
);
