// packages/react/src/components/TodoItem.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCircleCheck, faCircle } from '@fortawesome/free-regular-svg-icons';
import { faXmark } from '@fortawesome/free-solid-svg-icons';
import type { Todo } from 'shared-code/models/Todo';

type Props = {
    todo: Todo;
    onTodoCompleted: (todo: Todo) => void;
    onTodoDelete: (todo: Todo) => void;
};

export const TodoItem = ({ todo, onTodoCompleted, onTodoDelete }: Props) => (
    <div
        data-testid={`todo-${todo.id}`}
        className="flex gap-2 items-center justify-between border border-gray-400 dark:border-gray-500 rounded-lg px-2.5 py-2"
    >
        <button
            className="flex gap-2 items-center cursor-pointer group px-2 py-2"
            onClick={() => onTodoCompleted(todo)}
        >
            {todo.completed ? (
                <FontAwesomeIcon
                    icon={faCircleCheck}
                    title="Press to uncomplete"
                    className="text-xl text-green-500"
                />
            ) : (
                <FontAwesomeIcon
                    icon={faCircle}
                    title="Press to complete"
                    className="text-xl text-gray-400 group-hover:text-green-500 group-focus:text-green-500"
                />
            )}
            <span>{todo.description}</span>
        </button>
        <button
            onClick={() => onTodoDelete(todo)}
            className="group px-2 py-2"
            title="Press to remove"
        >
            <FontAwesomeIcon
                icon={faXmark}
                className="text-xl text-gray-400 group-hover:text-red-500 group-focus:text-red-500"
            />
            <span className="sr-only">Remove todo</span>
        </button>
    </div>
);

// packages/vue/src/components/TodoItem.vue
<script setup lang="ts">
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faCircle, faCircleCheck } from '@fortawesome/free-regular-svg-icons';
import { faXmark } from '@fortawesome/free-solid-svg-icons';
import type { Todo } from 'shared-code/models/Todo';

defineProps<{ todo: Todo }>();

const emit = defineEmits<{
    onTodoCompleted: [Todo];
    onTodoDelete: [Todo];
}>();
</script>

<template>
    <div
        :data-testid="`todo-${todo.id}`"
        class="flex gap-2 items-center justify-between border border-gray-400 dark:border-gray-500 rounded-lg px-2.5 py-2"
    >
        <button
            class="flex gap-2 items-center cursor-pointer group px-2 py-2"
            @click="emit('onTodoCompleted', todo)"
        >
            <FontAwesomeIcon
                v-if="todo.completed"
                :icon="faCircleCheck"
                title="Press to uncomplete"
                class="text-xl text-green-500"
            />
            <FontAwesomeIcon
                v-else
                :icon="faCircle"
                title="Press to complete"
                class="text-xl text-gray-400 group-hover:text-green-500 group-focus:text-green-500"
            />
            <span>{{ todo.description }}</span>
        </button>
        <button class="group px-2 py-2" title="Press to remove" @click="emit('onTodoDelete', todo)">
            <FontAwesomeIcon
                :icon="faXmark"
                class="text-xl text-gray-400 group-hover:text-red-500 group-focus:text-red-500"
            />
            <span class="sr-only">Remove todo</span>
        </button>
    </div>
</template>
